### PR TITLE
Correct semantics for string/number coercions

### PR DESCRIPTION
**Pull request by daurnimator**

### CODE REVIEW

**Comment by daurnimator** [comment]
Test failure makes me think travis hasn't grabbed new version of sprintf-js library.

**Comment by giann** [comment]
Yep, there's a flag in the .travis.yml which tells it to keep the yarn cache

**Comment by daurnimator** [comment]
> Yep, there's a flag in the .travis.yml which tells it to keep the yarn cache

Actually issue is yarn.lock file pinning to old version.

**Comment by giann** [comment]
Ah yes if you did not use it to update the module the lock file didn't change

**Comment by daurnimator** [comment]
Force-pushed to fix..

**Pull request merged**
